export const brakeDiscUserTable = [
  {
    field: "a_discDiameter",
    headerName: "A",
    darkColor: "text-sizeAcolor",
    ligthColor: "text-sizeAcolorLight",
    mainClass: "sizeA",
    placeholder: "260",
  },
  {
    field: "b_holeDiameter",
    headerName: "B",
    darkColor: "text-sizeBcolor",
    ligthColor: "text-sizeBcolorLight",
    mainClass: "sizeB",
    placeholder: "10.5",
  },
  {
    field: "c_numberOfHoles",
    headerName: "C",
    darkColor: "text-sizeCcolor",
    ligthColor: "text-sizeCcolorLight",
    mainClass: "sizeC",
    placeholder: "6",
  },
  {
    field: "d_center",
    headerName: "D",
    darkColor: "text-sizeDcolor",
    ligthColor: "text-sizeDcolorLight",
    mainClass: "sizeD",
    placeholder: "132",
  },
  {
    field: "e_holeDistance",
    headerName: "E",
    darkColor: "text-sizeEcolor",
    ligthColor: "text-sizeEcolorLight",
    mainClass: "sizeE",
    placeholder: "150",
  },
  {
    field: "f_width",
    headerName: "F",
    darkColor: "text-sizeFcolor",
    ligthColor: "text-sizeFcolorLight",
    mainClass: "sizeF",
    placeholder: "5",
  },
];
