export const connectingRodUserTable = [
  {
    field: "a_bigEnd",
    headerName: "A",
    darkColor: "text-sizeAcolor",
    ligthColor: "text-sizeAcolorLight",
    mainClass: "sizeA",
    placeholder: "22",
  },
  {
    field: "b_smallEnd",
    headerName: "B",
    darkColor: "text-sizeBcolor",
    ligthColor: "text-sizeBcolorLight",
    mainClass: "sizeB",
    placeholder: "14",
  },
  {
    field: "c_centerToCenter",
    headerName: "C",
    darkColor: "text-sizeCcolor",
    ligthColor: "text-sizeCcolorLight",
    mainClass: "sizeC",
    placeholder: "80",
  },
  {
    field: "d_totalLength",
    headerName: "D",
    darkColor: "text-sizeDcolor",
    ligthColor: "text-sizeDcolorLight",
    mainClass: "sizeD",
    placeholder: "106.25",
  },
  {
    field: "e_widthBigEnd",
    headerName: "E",
    darkColor: "text-sizeEcolor",
    ligthColor: "text-sizeEcolorLight",
    mainClass: "sizeE",
    placeholder: "13.5",
  },
  {
    field: "f_widthSmallEnd",
    headerName: "F",
    darkColor: "text-sizeFcolor",
    ligthColor: "text-sizeFcolorLight",
    mainClass: "sizeF",
    placeholder: "10.5",
  },
  {
    field: "g_eyeToEyeCenter",
    headerName: "G",
    darkColor: "text-sizeGcolor",
    ligthColor: "text-sizeGcolorLight",
    mainClass: "sizeG",
    placeholder: "60.5",
  },
  {
    field: "h_bigEndPinDiameter",
    headerName: "H",
    darkColor: "text-sizeHcolor",
    ligthColor: "text-sizeHcolorLight",
    mainClass: "sizeH",
    placeholder: "16",
  },
  {
    field: "i_bigEndPinLength",
    headerName: "I",
    darkColor: "text-sizeIcolor",
    ligthColor: "text-sizeIcolorLight",
    mainClass: "sizeI",
    placeholder: "40",
  },
];
