export const FSNarrowSplineTableData = [
  {
    displayName: "A",
    inputName: "a_innerMinimumDiameter",
    placeholder: "20.50",
    generalSize: "sizeA",
    baseColor: "text-sizeAcolor",
    hoverColor: "text-sizeAcolorLight",
  },
  {
    displayName: "B",
    inputName: "b_innerTeethNumber",
    placeholder: "23.50",
    generalSize: "sizeB",
    baseColor: "text-sizeBcolor",
    hoverColor: "text-sizeBcolorLight",
  },
  {
    displayName: "C",
    inputName: "c_innerMaximumDiameter",
    placeholder: "12",
    generalSize: "sizeC",
    baseColor: "text-sizeCcolor",
    hoverColor: "text-sizeCcolorLight",
  },
  {
    displayName: "D",
    inputName: "d_width",
    placeholder: "8.5",
    generalSize: "sizeD",
    baseColor: "text-sizeDcolor",
    hoverColor: "text-sizeDcolorLight",
  },
  {
    displayName: "E",
    inputName: "e_chain",
    placeholder: "520",
    generalSize: "sizeE",
    baseColor: "text-sizeEcolor",
    hoverColor: "text-sizeEcolorLight",
  },
];
