export const pistonKitUserTable = [
  {
    field: "a_compressionHight1",
    headerName: "A",
    darkColor: "text-sizeAcolor",
    ligthColor: "text-sizeAcolorLight",
    mainClass: "sizeA",
    placeholder: "22.5",
  },
  {
    field: "b_pinDiameter",
    headerName: "B",
    darkColor: "text-sizeBcolor",
    ligthColor: "text-sizeBcolorLight",
    mainClass: "sizeB",
    placeholder: "15",
  },
  {
    field: "c_compressionHight2",
    headerName: "C",
    darkColor: "text-sizeCcolor",
    ligthColor: "text-sizeCcolorLight",
    mainClass: "sizeC",
    placeholder: "22",
  },
  {
    field: "d_bore",
    headerName: "D",
    darkColor: "text-sizeDcolor",
    ligthColor: "text-sizeDcolorLight",
    mainClass: "sizeD",
    placeholder: "63.5",
  },
  {
    field: "e_length",
    headerName: "E",
    darkColor: "text-sizeEcolor",
    ligthColor: "text-sizeEcolorLight",
    mainClass: "sizeE",
    placeholder: "45.5",
  },
  {
    field: "f_pinLength",
    headerName: "F",
    darkColor: "text-sizeFcolor",
    ligthColor: "text-sizeFcolorLight",
    mainClass: "sizeF",
    placeholder: "48",
  },
  {
    field: "g_stroke",
    headerName: "G",
    darkColor: "text-sizeGcolor",
    ligthColor: "text-sizeGcolorLight",
    mainClass: "sizeG",
    placeholder: "4",
  },
];
