"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 piston.gltf --transform
Author: GoMeasure3D (https://sketchfab.com/gomeasure3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ktm-motorcycle-piston-artec-spider-3d-scan-d3ba01f398db4588bf6936b3b29b1b1d
Title: KTM Motorcycle Piston - Artec Spider 3D Scan
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Piston(props) {
  const { nodes, materials } = useGLTF("/piston-transformed.glb");

  materials.material_0.metalness = 1
  materials.material_0.roughness = 0.1
  materials.material_0.envMapIntensity = .5
  materials.material_0.color = { isColor: true, r: 0.9, g: 0.9, b: 0.9 }
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        position={[2.989, 0.791, 7.316]}
        rotation={[-2.454, -0.478, 0.268]}
      />
    </group>
  );
}

useGLTF.preload("/piston-transformed.glb");
