import Topbar from "@/Components/TopBar/TopBar";
import "./globals.css";
import { Inter } from "next/font/google";
import BottomBar from "@/Components/BottomBar/BottomBar";
import { SharedValuesProvider } from "@/Context/SharedValuesContext/SharedValuesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Size Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SharedValuesProvider>
        <body className={inter.className}>
          <div className="flex min-h-screen flex-col justify-between bg-gray-900">
            <Topbar />
            {children}
            <BottomBar />
          </div>
        </body>
      </SharedValuesProvider>
    </html>
  );
}
