export const sizeColors = {
  sizeAcolor: "#FF8383",
  sizeAcolorLight: "#FF2929",
  sizeBcolor: "#7CFF85",
  sizeBcolorLight: "#00DD21",
  sizeCcolor: "#FFBE45",
  sizeCcolorLight: "#FF6B07",
  sizeDcolor: "#83C5FF",
  sizeDcolorLight: "#0E3BFF",
  sizeEcolor: "#FFA160",
  sizeEcolorLight: "#FF3E07",
  sizeFcolor: "#D583FF",
  sizeFcolorLight: "#9600EA",
  sizeGcolor: "#9FFFF3",
  sizeGcolorLight: "#00F5FF",
  sizeHcolor: "#FFFE8A",
  sizeHcolorLight: "#E2EA00",
  sizeIcolor: "#977AFF",
  sizeIcolorLight: "#4A0BFF",
};
