"use client";
import { useContext, useState } from "react";
import PostForm from "@/Components/PostForm/PostForm";
import { SharedValuesContext } from "@/Context/SharedValuesContext/SharedValuesContext";
import { Metadata } from "next";

export const metadata: Metadata  = {
  title: "Size Match - Post Parts",
  description: "Generated by create next app",
};

const AdminCrud = () => {
  const { state, dispatch } = useContext(SharedValuesContext);
  const { frontSprocket } = state;

  const [hoverClass, setHoverClass] = useState("");

  // conecta el hover del svg con el formulario
  const handleHover = (
    e: React.MouseEvent<
      SVGPathElement | SVGTextElement | HTMLHeadingElement,
      MouseEvent
    >
  ) => {
    const { classList } = e.target as HTMLElement;
    setHoverClass(classList[0]);
  };

  const handleMouseLeave = () => {
    setHoverClass("");
  };

  const handleFSChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    const newValue = value.replace(/[^0-9.]/g, "");

    dispatch({
      type: name,
      payload: newValue,
      group: "frontSprocket",
    });
  };

  return (
    <div className="mx-auto my-5 ">
      <PostForm
        handleFSChange={handleFSChange}
        handleHover={handleHover}
        handleMouseLeave={handleMouseLeave}
      />
    </div>
  );
};

export default AdminCrud;
