"use client";
import PostForm from "@/Components/PostForm/PostForm";
import TableAdmin from "@/Components/TableAdmin/TableAdmin";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Size Match - Post Parts",
  description: "Generated by create next app",
};

const AdminCrud = () => {
  return (
    <div className="mx-auto my-5 ">
      <PostForm />
      <TableAdmin/>
    </div>
  );
};

export default AdminCrud;
